parameters: {}
environment: {}
packages:
  - name: linebot
    environment: {}
    parameters: {}
    actions:
      - name: webhook
        main: ''
        runtime: 'go:default'
        environment: {
          AUTH_TOKEN: 'YOUR_AUTH_TOKEN_HERE',
          BOT_TOKEN: 'YOUR_LINEBOT_TOKEN_HERE'
        }
        parameters: {}

